sudo: required
before_script:
  - sudo apt-get install g++-6 cmake python-pip libboost-all-dev
  - sudo pip install conan
  
# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc

# Build steps
script:
  - conan install .
  - mkdir build
  - cd build
  - cmake .. && make
  - cd bin
  - ./unitTest
